api/cf/cfv2/api_service.go
api/cf/cfv2/private_domain.go
api/cf/cfv2/routes.go
api/cf/cfv2/service_bindings.go
api/cf/cfv2/shared_domain.go
examples/cf/app/main.go
examples/cf/route/main.go

Add API to FindByName the shared or private domain for route .

Add shared and private domain for route

---

api/cf/cfv2/routes.go
examples/cf/route/main.go

The API for route delete is fixed.

Fix route delete

---

api/cf/cfv2/private_domain.go

Find a private domain without specifying org details.

Find Private domain without specifying Org

---

api/cf/cfv2/private_domain.go
examples/cf/privatedomain/README.md
examples/cf/privatedomain/main.go

Add private domain API support to perform CURD operations.

Private Domain API

---

api/cf/cfv2/shared_domain.go
examples/cf/shareddomain/README.md
examples/cf/shareddomain/main.go

Add shared domain API support for CURD operations.

Shared domain API

---

api/cf/cfv2/spaces.go
examples/cf/route/main.go

List all filtered routes based on host,port and path from a user space.

List filter matched routes in space

---

api/account/accountv2/accounts.go
api/account/accountv2/accounts_test.go

Signed-off-by: Ross Pavitt <pavittr@uk.ibm.com>

Add GUID to struct returned from individual response

---

README.md

Signed-off-by: Hui Kang <kangh@us.ibm.com>

Fix typo and format in README

---

api/container/containerv1/clusters.go
api/container/containerv1/clusters_test.go

Otherwise those values are always false. Test case extended as well.

Vlan struct's IsByOIP and IsPublic has to be json tagged

---

api/mccp/mccpv2/service_instances.go

- async is set to true by default
- fix #60
Co-authored-by: Ashish Kumar Thakur
Signed-off-by: Hui Kang <kangh@us.ibm.com>

Service instance DELETE method: Add asyncs parameter

---

Makefile
api/account/accountv1/accounts.go
api/account/accountv1/accounts_test.go
api/account/accountv1/accountv1_suite_test.go

I noticed this functionality was missing, so I've decided to submit a PR to add it. I've also included unit tests for my functionality changes as well.

Adds account user invite / delete functions

---

api/icd/icdv4/connection.go
examples/icd/icdv4/cdb/README.md
examples/icd/icdv4/connection/README.md
examples/icd/icdv4/connection/main.go
examples/icd/icdv4/scalingGet/README.md
examples/icd/icdv4/scalingUpdate/README.md
examples/icd/icdv4/scalingUpdate/main.go
examples/icd/icdv4/task/README.md
examples/icd/icdv4/user/README.md
examples/icd/icdv4/user/main.go
examples/icd/icdv4/userpassword/README.md
examples/icd/icdv4/whitelist/README.md
examples/icd/icdv4/whitelist/main.go

Add mongodb support and minor updates to Readme's.

add mongodb support

---

api/cis/cisv1/dns.go
api/cis/cisv1/paginate.go

Convert ListDns to return all results instead of just first page

---

api/usermanagement/usermanagementv2/models.go
examples/usermanagement/user_invite/main.go

The PR has fix for: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1114
Updated the user invite structure member - classic infra roles.

fixed user_invite issue

---

api/container/containerv2/clusters.go
api/container/containerv2/clusters_test.go
examples/container/V2containers/CreateClusterV2/main.go

added support for cos instance CRN param in cluster creation

added support for cos instance CRN param in cluster creation

---

api/cse/csev2/serviceendpoints.go
api/cse/csev2/serviceendpoints_test.go

Support the following API calls for CSE APIv2 Service Endpoints:
- GET /v2/serviceendpoints to Get all service endpoint instances.
- PATCH /v2/serviceendpoint/{serviceid} to Patch/Update the service endpoint instance (note: there is a `action` for the operation which could `add` or `delete`).
Functional tests are done and passed for these calls.
Background:
In IBM Cloud Kubernetes service, we would like to manage service endpoints from go code, and this module would be useful. That's why we would like to follow the API description as is.

Add support for list and patch operations

---

api/usermanagement/usermanagementv2/models.go
api/usermanagement/usermanagementv2/user_invite.go
examples/usermanagement/user_invite/README.md
examples/usermanagement/user_invite/main.go

IBM Cloud console access restriction: Partially update user settings

IBM Cloud console access restriction: Partially update user settings

---

api/container/containerv1/api_service.go
api/container/containerv1/kms.go
api/container/containerv1/kms_test.go
api/container/containerv2/api_service.go
api/container/containerv2/kms.go
api/container/containerv2/kms_test.go
examples/container/V2containers/EnableKmsV2/README.md
examples/container/V2containers/EnableKmsV2/main.go
examples/container/kms/README.md
examples/container/kms/main.go

Resource: Cluster KMS Enable

---

api/container/containerv2/clusters.go
api/container/containerv2/clusters_test.go

Added support to list satellite cluster along with vpc clusters

Support to list satellite cluster

---

endpoints/endpoints.go

Should fix https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1894 (cannot manage ICD databases in Chennai with terraform)

Add ICD endpoint for Chennai

---

api/iamuum/iamuumv2/access_group.go
examples/iamuum/access_group/README.md
examples/iamuum/access_group/main.go

Fetching user level access groups

---

api/usermanagement/usermanagementv2/pagination.go
api/usermanagement/usermanagementv2/user_invite.go
examples/usermanagement/user_invite/main.go

Fetch all usesr in an account

---

api/container/containerv1/clusters.go
examples/container/build/main.go
helpers/zip.go
trace/trace.go

static scan fixes

---

api/iampap/iampapv1/v1_policies.go

Adding search query for PAP
Co-authored-by: Rajesh Pirati <Rajesh.Pirati@ibm.com>
Co-authored-by: Bhavana Bellamgari <bhavana.bellamgari@ibm.com>
Co-authored-by: Rudrasish Pradhan <rudrasish.pradhan@ibm.com>

Adding search params for PAP

---

api/container/containerv2/api_service.go
api/container/containerv2/ob_logging.go
api/container/containerv2/ob_logging_test.go
api/container/containerv2/ob_monitoring.go
api/container/containerv2/ob_monitoring_test.go
examples/container/V2containers/CreateLoggingV2/main.go
examples/container/V2containers/CreateMonitoringV2/main.go
examples/container/V2containers/DeleteLoggingV2/main.go
examples/container/V2containers/DeleteMonitoringV2/main.go
examples/container/V2containers/GetLoggingV2/main.go
examples/container/V2containers/GetMonitoringV2/main.go
examples/container/V2containers/ListLoggingV2/main.go
examples/container/V2containers/ListMonitorsV2/main.go
examples/container/V2containers/UpdateLoggingV2/main.go
examples/container/V2containers/UpdateMonitoringV2/main.go

Support sysdig monitor  logDNA

Sysdig monitor support in cluster

---

api/container/containerv2/ob_logging.go
api/container/containerv2/ob_monitoring.go
examples/container/V2containers/CreateLoggingV2/README.md
examples/container/V2containers/CreateLoggingV2/main.go
examples/container/V2containers/CreateMonitoringV2/README.md
examples/container/V2containers/CreateMonitoringV2/main.go
examples/container/V2containers/DeleteLoggingV2/README.md
examples/container/V2containers/DeleteLoggingV2/main.go
examples/container/V2containers/DeleteMonitoringV2/README.md
examples/container/V2containers/DeleteMonitoringV2/main.go
examples/container/V2containers/GetLoggingV2/README.md
examples/container/V2containers/GetLoggingV2/main.go
examples/container/V2containers/GetMonitoringV2/README.md
examples/container/V2containers/GetMonitoringV2/main.go
examples/container/V2containers/ListLoggingV2/README.md
examples/container/V2containers/ListLoggingV2/main.go
examples/container/V2containers/ListMonitorsV2/README.md
examples/container/V2containers/ListMonitorsV2/main.go
examples/container/V2containers/UpdateLoggingV2/README.md
examples/container/V2containers/UpdateLoggingV2/main.go
examples/container/V2containers/UpdateMonitoringV2/README.md
examples/container/V2containers/UpdateMonitoringV2/main.go

Changed DeleteConfig call from DELETE to POST

---

api/container/containerv2/ob_logging.go
api/container/containerv2/ob_monitoring.go
examples/container/V2containers/DeleteLoggingV2/main.go
examples/container/V2containers/DeleteMonitoringV2/main.go

Handling unmarshal error on DELETE request

Handling unmarshal error on DELETE request

---

api/certificatemanager/certificate.go
api/certificatemanager/paginate.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2358

Support: Pagination on Listing Certificates

---

endpoints/endpoints.go

This will fix IBM-Cloud/terraform-provider-ibm#2489

Add ICD endpoint for Toronto

---

.legal.yaml

This file is required for the OSS approval process.

Added the .legal.yaml

---

client/client.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2892

Fix: token refresh on session inactivity

---

api/container/containerv2/api_service.go
api/container/containerv2/satellite.go
api/satellite/satellitev1/api_service.go
api/satellite/satellitev1/endpoint.go
endpoints/endpoints.go

1. Added new endpoint locator for returning the link endpoint
2. Added new container-v2 API to get location details
3. Added GET,POST,DELETE for satellite endpoints
Signed-off-by: Tapas Sharma <tapas@portworx.com>

Added support for Satellite-v1 Endpoints API

---

api/container/containerv2/openshift.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2811#issuecomment-876368681

Support: service API Key for cluster config

---

Makefile
api/container/containerv1/alb.go
api/container/containerv1/alb_test.go
api/container/containerv2/alb.go
api/container/containerv2/alb_test.go
examples/container/V2containers/CreateAlbV2/main.go
examples/container/albcreate/README.md
examples/container/albcreate/main.go

Adding CreateALB to be able to create NEW ALBs for Classic Clusters
Updated V2 CreateALB to provide return value of the response.

Classic create alb

---

api/icd/icdv4/connection.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3454

Support:  Mysql

---

api/container/containerv1/clusters.go
api/container/containerv2/clusters.go
examples/container/image_security/README.md
examples/container/image_security/main.go

Pull request providing API functions for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3344.
Example should allow anyone with an access to a classic/VPC cluster to set image security enforcement programatically.

Set image security

---

api/icd/icdv4/scaling.go

Related to https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3562

Fix: scale down database to 0

---

api/container/containerv2/clusters.go
api/container/containerv2/clusters_test.go
api/container/containerv2/worker_pool_test.go

add kms account id to kms config, allowing use of keys provided by different accounts

add kms account id to kms config

---

api/container/containerv2/clusters.go
api/container/containerv2/clusters_test.go
api/container/containerv2/worker_pool_test.go

Add kms account

---

api/container/containerv2/ingress.go
api/container/containerv2/ingress_test.go
examples/container/V2containers/IngressV2/main.go

- add ingress instance models
- update ingress secret models for opaque secrets
- expand current ingress client interface to include instance functionality

add ingress instance functionality

---

api/container/containerv2/ingress.go
api/container/containerv2/ingress_test.go
examples/container/V2containers/IngressV2/main.go

- add ingress secret field support to remove and add fields

add ingress secret field support

---

api/satellite/satellitev1/source.go
examples/satellite/main.go

Added UpdateSatelliteEndpointSources() API for updating satellite endpoint source.

Added UpdateSatelliteEndpointSources() API for updating satellite endpoint source.

---

api/account/accountv1/accounts.go
api/account/accountv1/accounts_test.go
models/accouts.go

This PR is to move account managements API verison from v1 to v2

Move account from version v to v2

---

api/container/containerv1/kms.go
api/container/containerv1/kms_test.go
api/container/containerv2/kms.go
api/container/containerv2/kms_test.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4745

add optional AccountID to KmsEnableReq

---

api/container/containerv2/vpcs.go
api/container/containerv2/vpcs_test.go

Support the new API endpoint `/network/v2/outbound-traffic-protection`

Support outbound-traffic-protection
