IBM-Cloud/bluemix-go

api/mccp/mccpv2/service_instances.go
- as recommended by cloudfoundry API [1]
[1] https://apidocs.cloudfoundry.org/272/service_instances/delete_a_service_instance.html
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Set async to true when deleting an instance

api/cis/cisv1/dns.go, api/cis/cisv1/dns_test.go, api/cis/cisv1/glbs.go, api/cis/cisv1/glbs_test.go, api/cis/cisv1/monitors.go, api/cis/cisv1/monitors_test.go, api/cis/cisv1/pools.go, api/cis/cisv1/pools_test.go, api/cis/cisv1/zones.go, api/cis/cisv1/zones_test.go, api/mccp/mccpv2/apps.go, api/mccp/mccpv2/service_instances.go, helpers/conversion.go
Changed returns types of *[]<T> to just []<T>, *[] aren't rangeable and
don't provide any benefit as [] is a pointer.
Also some struct fields for json responses weren't exported so could not
have been populated.
Also removed helper functions for providing pointers to slices and maps
=> Remove pointers to slices

api/container/containerv1/versions.go, examples/container/versions/main.go
Implemented #155 
Signed-off-by: Yu Wei <yuweiw@cn.ibm.com>
Output after running examples code examples/container/versions is as below,
```
weis-mbp:versions weiyu$ go run main.go 
[{1 12 10 false} {1 13 11 false} {1 14 7 true} {1 15 4 false}]
map[kubernetes:[{1 12 10 false} {1 13 11 false} {1 14 7 true} {1 15 4 false}] openshift:[{3 11 146 false}]]
```
=> Support /v1/versions to get openshift versions.

api/container/containerv1/versions.go
To support /v1/versions,  type `V1Version` should be exported.
=> /v1/versions support, fix typo

api/cis/cisv1/dns.go, api/cis/cisv1/dns_test.go, api/cis/cisv1/glbs.go, api/cis/cisv1/glbs_test.go, api/cis/cisv1/monitors.go, api/cis/cisv1/pools.go, api/cis/cisv1/pools_test.go
Connects to issue https://github.com/IBM-Cloud/bluemix-go/issues/149
Also adds Description field to `MonitorBody` https://github.com/IBM-Cloud/bluemix-go/compare/master...BobbyRadford:fix-cis-sdk?expand=1#diff-80f206b5690fe621962afc049c13b41cR40
=> Use PUTs for CIS resource update calls

client/client.go
Observed error..
```
Request failed with status code: 520, ServerErrorResponse: <!DOCTYPE html>
<html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">
<title>us-south.containers.cloud.ibm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
```
Ideally, 520 errors should be included in the retry list as well.
=> fix: Support for retry on 520 status code

api/container/containerv1/clusters.go, api/container/containerv1/clusters_test.go
No ServerURL property returned for the VPC cluster . See the below rest api output>
Used masterURL as a Server URL for VPC clusters 
```
root@prgavali1:~/go_workspace/src/test-go# curl -X GET -H "Authorization: $IAM_TOKEN" -H "Content-Type: application/json" "https://containers.cloud.ibm.com/v2/getCluster?v1-compatible&cluster=mycluster2-gen2" | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1585  100  1585    0     0    762      0  0:00:02  0:00:02 --:--:--   762
{
"id": "bqp9aj9d0b914bomgo8g",
"name": "mycluster2-gen2",
"region": "us-south",
"resourceGroup": "590a67db1ed242afbfaac997650133e5",
"resourceGroupName": "default",
"createdDate": "2020-05-06T10:45:33+0000",
"masterKubeVersion": "1.17.6_1526", …
```
=> Handled ServerURL/MasterURL for the vpc clusters

models/resource_service_instance.go
We(Event Streams) store instance connection information in `instance.extensions.api-url`, would like to get this from API response and initialize the connection for our terraform support.
=> add extensions in instance

endpoints/endpoints.go
To be able to manage databases inside the `eu-fr2` region we need
to define the API endpoint.
=> Add `eu-fr2` as valid ICD endpoint

api/container/containerv1/worker_pool.go
* added UpdateLabelsWrokerPool
This to support Feature request: have "label" property in "ibm_container_cluster" 775 in the terraform-provider-ibm repo
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/775  
This PR is required by https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1940
=> added UpdateLabelsWrokerPool (#1)

api/container/containerv1/clusters.go
Looks like there is an extra message, perhaps left over from debugging, which will leak tokens over `stdout`.
=> fix: Remove extra println statement

api/container/containerv2/workers.go, examples/container/V2containers/AttachStorageV2/main.go
This PR supports:
VPC volume attachment operations on IKS cluster worker node.
=> Added support for vpc volume attachment

endpoints/endpoints.go
Make it possible to launch ICD (IBM Cloud Databases) databases in the
jp-osa region.
=> jp-osa: Add ICD API endpoint

endpoints/endpoints.go, endpoints/endpoints_test.go
Signed-off-by: James Hart <jhart@uk.ibm.com>
The previous settings use deprecated bluemix.net domains. There are a couple of specific problems:
- Newer registry instances (jp-tok and jp-osa) do not have bluemix.net. The previous setting for `jp-tok` would not have worked.
- us-east should not really have been on the list. Unless there is a strong requirement to invisibly map us-east to the us-south registry, I think it is clearer to remove it.
=> Use icr.io domain endpoints for Container Registry

api/cis/cisv1/dns.go
Keeps with the rest of the methods pattern of no logging output. Leave the decision to log to the caller, not the method, IMO.
=> Update logging in dns.go in cisv1 package 

api/container/containerv2/clusters.go
In case of v2 we should call global/v2/getCluster not /v2/vpc/getCluster
Corrected the endpoint, tested with ibmcloud cli and small test program.
Signed-off-by: Tapas Sharma <tapas@portworx.com>
=> Correcting the API endpoint to be called to get ClusterInfo

api/container/containerv2/openshift.go
This PR increases the robustness of the openshift login flow:
- Retries on retrieving the passcode ( including covering of the rate limit that kicks in)
- Race condition (around request headers) that existed in previous version as the same rest client instance was reused without proper locking. Some threads in previous code was effectively essentially removing the auth headers causing any parallel and subsequent request to fail with 401.
- Exiting with error when passcode cannot be retrieved - ensuring the user is not unexpectedly authenticated as 'anonymous'
- Handling of intermittent issue where openshift returns a 200 instead of a 302 with accesscode on authentication flow
Context: We've been plagued with a number of authentication / login issue in our terraform code. The IBM Cloud …
=> fix: Increase robustness of openshift login flow

api/satellite/satellitev1/endpoint.go
With the new json response Endpoints for a satellite location have moved inside
a first level struct, made those changes so that json.Marshal does not throw an error
Signed-off-by: Tapas Sharma <tapas@portworx.com>
=> Added support for json marshalling for JSON getEndpoints call

api/container/containerv2/worker_pool.go, api/container/containerv2/worker_pool_test.go
Added `ResizeWorkerPool()` API to container V2.
Corrosponding REST API definition: https://cloud.ibm.com/apidocs/kubernetes#v2resizeworkerpool
=> :zap: Added support for ResizeWorkerPool() API in containerv2

api/icd/icdv4/scaling.go
IsOptional flag on Group types determines whether resource can have 0 allocations. This information was missing.
=> Add IsOptional flag to scaling types

api/container/containerv2/clusters.go, api/container/containerv2/clusters_test.go
added 
KmsInstanceID     string            `json:"kmsInstanceID,omitempty"`
WorkerVolumeCRKID string            `json:"workerVolumeCRKID,omitempty"`
fields to  type WorkerPoolConfig struct
=> update v2 to handle boot volume encryption from create

api/container/containerv2/clusters_test.go, api/container/containerv2/worker_pool.go, api/container/containerv2/worker_pool_test.go, examples/container/V2containers/CreateClusterV2/main.go, examples/container/V2containers/GetWorkerpoolV2/main.go
this PR extends the cluster and workerpool operations with SecondaryStorageOption
https://containers.cloud.ibm.com/global/swagger-global-api/#/v2/getWorkerPool
https://containers.cloud.ibm.com/global/swagger-global-api/#/v2/vpcCreateCluster
https://containers.cloud.ibm.com/global/swagger-global-api/#/v2/vpcCreateWorkerPool
tested with the below examples:
```
CreateClusterV2 % go run main.go -vpcid <vpcid> -subnetid <subnetid> -secondarystorage 900gb.5iops-tier -zone <zoneid> -name zoza-test 
...
Cluster create request was successful
Response: {<clusterid>}
---------------------------
GetWorkerpoolV2 % go run main.go -cluster <clusterid> -workerpool default
...
Get workerpool request was successful
Response: {"flavor":"bx2.4x16","id":"<workerpoolid>","isolation":"public","labels":{"ibm-clou …
```
=> add SecondaryStorageOption to cluster and workerpool operations

api/container/containerv1/addons.go
List available add-ons that you can enable in a cluster. For each available add-on, the name, latest version, and minimum Kubernetes version required to run the add-on in a cluster are returned.
https://containers.cloud.ibm.com/global/swagger-global-api/#/util/GetAddons
=> List Addon Support

api/container/containerv1/worker_pool.go, api/container/containerv1/worker_pool_test.go, api/container/containerv2/worker_pool.go, api/container/containerv2/worker_pool_test.go, examples/container/getWorkerPool/main.go
I've tested with the following scenario:
- create a cluster with the autoscaler addon
- get the workerpool with the example code and verify the autoscaleEnabled==false
- try to resize the workerpool and verify that terraform tries to do it
- enable autoscaling for the workerpool
- get the workerpool again and verify the autoscaleEnabled==true
- try to resize the workerpool and verify that terraform ignores it
logs from VPC test:
```
% terraform apply
Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
+ create
<= read (data resources)
Terraform will perform the following actions:
<= data "ibm_container_cluster_config" "cluster_config"  {
...
+ resource "ibm_container_addons" "addons" {
+ cluster …
```
=> add AutoscaleEnabled to WorkerPoolResponses

api/container/containerv2/clusters.go, api/container/containerv2/openshift.go, api/container/containerv2/openshift_test.go
- in case of Openshift, honor the endpoint type when generating the token based kubeconfig
Test: ROKS 4.12 on VPC (Public Service Endpoint is disabled)
1. Both configs contain the Private Service Endpoint - as that is the default for the cluster.
```
➜ go run main.go -clustername ck6414bl0a61qv1bo690 -path /Users/adam/terraform/terraform_output
➜ cat /Users/adam/terraform/terraform_output/6189e52cfb76e60b485d8d90acc513b9337734242accf8dbfbbb943f777f92d8_ck6414bl0a61qv1bo690_k8sconfig/config.yml      
apiVersion: v1
clusters:
- cluster:
server: https://c108-e.private.eu-gb.containers.cloud.ibm.com:31579
name: console-vpe-412/ck6414bl0a61qv1bo690
- cluster:
server: https://c108-e.private.eu-gb.containers.cloud.ibm.com:31579
name: c108-e-private-eu-gb-containers-cloud-ibm-com:31579
contexts: …
```
=> Containers API - cluster config update

api/container/containerv2/openshift.go
- fix for VPC ROKS clusters with public and private service endpoints enabled
- in this case, VPE cannot be used for the token generation function, need to ignore it
=> containers API - Option VPE can be used only if the Public Service Endpoint is disabled

api/container/containerv2/clusters.go, api/container/containerv2/openshift.go
- in case Openshift, the clusterHost ouptut value should be set with same value as the generated kubeconfig with FetchOCTokenForKubeConfig
- the ealier solution was added the host from the first kubeconfig context (got from Containers API)
Related to https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4861
=> Fix return values of cluster_config 

api/container/containerv2/clusters.go, examples/container/V2containers/GetClusterV2/main.go
Using the API `global/v2/getCluster?=cluster<id>&v1-compatible` there are different return values depending on the provider.
For VPC clusters, masterHealth (and other master fields) can be checked in the lifecycle resource. Classic clusters don't have this resource and instead call masterHealth directly.
Downstream, the observability terraform provider needs to be able to check masterHealth to confirm the cluster is ready to deploy. So this PR is adding masterHealth to the cluster struct.
=> add masterHealth field to cluster struct

api/container/containerv2/worker_pool.go, api/container/containerv2/worker_pool_test.go, api/container/containerv2/workers.go, api/container/containerv2/workers_test.go
New endpoint needed for terraform. For testing against the real endpoint see the terraform PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5589
```
% go test ./api/container/containerv2/ -ginkgo.focus "SetWorkerPoolOperatingSystem"
ok      github.com/IBM-Cloud/bluemix-go/api/container/containerv2       90.970s
```
=> Add new SetWorkerPoolOperatingSystem api

api/container/containerv2/workers.go, api/container/containerv2/workers_test.go
Changes `ListClassicWorkers` to `ListAllWorkers`, as the endpoint `/v2/classic/getWorkers` only exists in the regional APIs, causing 404s when requesting through global API.
Example response from endpoint:
```json
[
{
"id": "someID",
"lifecycle": {
"desiredState": "deployed",
"actualState": "deployed",
"message": "",
"messageDate": "",
"pendingOperation": "",
"reasonForDelete": "",
"messageDetails": "",
"messageDetailsDate": "",
"desiredOperatingSystem": "UBUNTU_24_64",
"actualOperatingSystem": "UBUNTU_24_64"
},
"health": {
"state": "normal",
"message": "Ready"
},
"kubeVersion": {
"desired": "1.30.5_1542",
"actual": "1.30.5_1542",
"target": "1.30.5_1542",
"eos": "",
"masterEOS": ""
},
"flavor": "fla",
"location": "loc",
"poolID": "someID-poolID",
"poolName": "default", …
```
=> Changed v2/classic/getWorkers to v2/getWorkers

api/container/containerv2/vpcs.go, api/container/containerv2/vpcs_test.go
Connected terraform-provider PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5751
=> Support enable secure-by-default
